import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy - CareNote",
  description: "CareNote Privacy Policy. Learn how we collect, use, and protect your data.",
}

export default function PrivacyPolicyPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground">Privacy Policy</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: April 2026</p>
      </div>

      <p className="text-muted-foreground leading-relaxed">
        CareNote (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting the
        privacy of our users and the individuals whose information is processed through our platform.
        This Privacy Policy describes how we collect, use, store, and share information when you use
        the CareNote application and related services (collectively, the &quot;Service&quot;).
      </p>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">1. Information We Collect</h2>
        <p className="text-muted-foreground leading-relaxed">
          We collect the following categories of information in connection with your use of the Service:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
          <li>
            <span className="font-medium text-foreground">Voice Recordings:</span> Audio data captured
            during voice documentation sessions initiated by caregivers. These recordings are processed
            in real time and are not retained after transcription unless otherwise configured by your
            organization.
          </li>
          <li>
            <span className="font-medium text-foreground">Transcripts:</span> Text transcriptions
            generated from voice recordings, used to produce structured care documentation.
          </li>
          <li>
            <span className="font-medium text-foreground">Patient Care Notes:</span> Structured clinical
            notes, including resident observations, care activities, incident reports, and behavioral
            documentation generated by our AI from your voice input.
          </li>
          <li>
            <span className="font-medium text-foreground">Account Information:</span> Name, email address,
            role, and organizational affiliation provided during account registration and use.
          </li>
          <li>
            <span className="font-medium text-foreground">Usage Data:</span> Information about how you
            interact with the Service, including session timestamps, feature usage, and device information.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">2. How We Use Your Information</h2>
        <p className="text-muted-foreground leading-relaxed">
          We use the information we collect for the following purposes:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
          <li>
            <span className="font-medium text-foreground">AI-Powered Documentation:</span> Processing
            voice recordings through our AI pipeline to generate structured, clinically relevant care notes.
          </li>
          <li>
            <span className="font-medium text-foreground">Incident Detection:</span> Automatically
            identifying and flagging potential incidents such as falls, behavioral changes, or medication
            concerns within care documentation.
          </li>
          <li>
            <span className="font-medium text-foreground">Family Updates:</span> Generating summaries
            and updates for authorized family members based on care documentation, where enabled by the
            organization.
          </li>
          <li>
            <span className="font-medium text-foreground">Service Improvement:</span> Analyzing
            aggregated, de-identified usage patterns to improve the accuracy and reliability of our
            AI models and overall Service quality.
          </li>
          <li>
            <span className="font-medium text-foreground">Account Administration:</span> Managing user
            accounts, authentication, and organizational access controls.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">3. Data Storage and Security</h2>
        <p className="text-muted-foreground leading-relaxed">
          All data is stored using Supabase, a secure cloud database platform. We implement the following
          security measures:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
          <li>All data is encrypted at rest and in transit using industry-standard encryption protocols.</li>
          <li>Row-Level Security (RLS) policies ensure that users can only access data belonging to their
            organization.</li>
          <li>Role-based access controls restrict data access based on user roles within the organization.</li>
          <li>Regular security audits and monitoring are conducted to identify and address potential
            vulnerabilities.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">4. Third-Party Service Providers</h2>
        <p className="text-muted-foreground leading-relaxed">
          We use the following third-party services to deliver the Service. Each provider processes data
          only as necessary to perform their designated function:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
          <li>
            <span className="font-medium text-foreground">Vapi:</span> Provides voice AI infrastructure
            for real-time voice interaction and call management.
          </li>
          <li>
            <span className="font-medium text-foreground">Anthropic (Claude):</span> Processes transcripts
            to generate structured care notes, detect incidents, and provide AI-powered clinical
            documentation assistance.
          </li>
          <li>
            <span className="font-medium text-foreground">OpenAI (Whisper):</span> Provides
            speech-to-text transcription for voice notes recorded outside the conversational
            Vapi flow. Audio is streamed directly to the transcription endpoint and is not
            persisted by CareNote.
          </li>
          <li>
            <span className="font-medium text-foreground">Resend:</span> Delivers transactional
            email (family updates, clinician portal invitations). Email bodies include only the
            content needed for that notification.
          </li>
          <li>
            <span className="font-medium text-foreground">Supabase:</span> Hosts our database
            and authentication infrastructure.
          </li>
        </ul>
        <p className="text-muted-foreground leading-relaxed">
          We require all third-party providers to maintain appropriate security standards and to process
          data only in accordance with our instructions and applicable law. HIPAA Business Associate
          Agreements with each sub-processor are finalized at the time of customer onboarding alongside
          the BAA with CareNote.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">5. Data Retention</h2>
        <p className="text-muted-foreground leading-relaxed">
          We retain care documentation and associated data for as long as your organization maintains
          an active account, or as required by applicable healthcare regulations and record-keeping
          requirements. Voice recordings are processed in real time and are not stored beyond the
          duration necessary to complete transcription, unless your organization has configured
          extended retention.
        </p>
        <p className="text-muted-foreground leading-relaxed">
          Upon account termination, we will delete or de-identify your data within 90 days, except
          where retention is required by law.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">6. Your Rights</h2>
        <p className="text-muted-foreground leading-relaxed">
          Depending on your jurisdiction, you may have the following rights with respect to your
          personal information:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
          <li>
            <span className="font-medium text-foreground">Access:</span> Request a copy of the personal
            information we hold about you.
          </li>
          <li>
            <span className="font-medium text-foreground">Correction:</span> Request correction of
            inaccurate or incomplete personal information.
          </li>
          <li>
            <span className="font-medium text-foreground">Deletion:</span> Request deletion of your
            personal information, subject to applicable legal retention requirements.
          </li>
          <li>
            <span className="font-medium text-foreground">Data Export:</span> Request a portable copy
            of your data in a commonly used, machine-readable format.
          </li>
          <li>
            <span className="font-medium text-foreground">Opt-Out:</span> Opt out of certain data
            processing activities where applicable.
          </li>
        </ul>
        <p className="text-muted-foreground leading-relaxed">
          To exercise any of these rights, please contact us using the information provided below.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">7. Contact Us</h2>
        <p className="text-muted-foreground leading-relaxed">
          If you have questions or concerns about this Privacy Policy or our data practices, please
          contact us at:
        </p>
        <p className="text-muted-foreground">
          Email:{" "}
          <a href="mailto:support@carenote.app" className="text-primary underline hover:no-underline">
            support@carenote.app
          </a>
        </p>
      </section>
    </div>
  )
}
